#!/bin/bash

### SETUP

## APACHE VARIABLES
# Command to restart web server
APACHE_RESTART_CMD="sudo /etc/init.d/httpd restart"
# Domain name of the host
APACHE_DOMAIN="127.0.0.1"
# Apache vhost file.
APACHE_VHOST=/etc/httpd/conf/httpd.conf
# Root directory for all browser instances.
APACHE_BROWSER_ROOT=""
# Location where to store each home page
BROWSER_WEB_HOME=/var/www/html

## MySQL VARIABLES
# Mysql user name that has priviledges to create a database
MYSQL_USER=root
# Command for MySQL. 
# Add "-p" to the command below to specify that a password is required for this user i.e., "mysql -u $MYSQL_USER -p"
MYSQL_CMD="mysql -u $MYSQL_USER"
# MySQL user with read-only access
READONLY_USER=readonly
READONLY_PASSWORD=access
# MySQL user with read/write access
READWRITE_USER=browser
READWRITE_PASSWORD=genome
# Host where the MySQL database resides (default same as Apache i.e. localhost)
DB_HOST="localhost"

## UCSC INSTALL VARIABLES
# Path to UCSC binaries e.g. hgLoadBed, faToTwoBit, gfServer, etc.
UCSC_BIN=/gbdb/bin
# Gzip TAR archive that contains the UCSC Genome Browser CGI binaries and HTML files.
BROWSER_WEB_TEMPLATE_DIST=${BROWSER_WEB_HOME}/browser.tar.gz
# Location to store the genome builds and tracks
GBDB_DIR=/gbdb
# Source code for the UCSC Genome Browser, specifically the src/hg/lib directory
KENT_LIB=/gbdb/jksrc/kent/src/hg/lib/
# Location of the trackDb directory i.e. where to store the trackDb.ra files.
TRACKDB_DIR=/gbdb/jksrc/kent/src/hg/makeDb/trackDb

# !!! DO NOT MODIFY THESE VARIABLES !!!
export PATH=$PATH:${UCSC_BIN}
INSTALL_DIR=`dirname $0`
SCRIPT_DIR=${INSTALL_DIR}/scripts

## FUNCTIONS

function task_message {
    echo "CGB: >> EXECUTING TASK ${TASK} FOR CLIENT ${CLIENT_NAME} <<"
}

# Runs MySQL command for the CLIENT_NAME HGCENTRAL database
function mysql_hgcentral {
    MYSQL_STATEMENT=$1
    HGSQL_CMD="hgsql ${CLIENT_HGCENTRAL} -e \"$MYSQL_STATEMENT\""
    echo "CGB: ** YOUR MYSQL PASSWORD POSSIBLY REQUIRED **"
    echo "CGB: Executing $HGSQL_CMD"
    until eval $HGSQL_CMD; do
    	echo -n "CGB: Invalid password or MySQL error ... retry? (Y/n): "
	read ans
	if [ "$ans" = 'n' ];
	then
	    break;
	fi
    done
}

# Init basic track definitions
function init_trackDb {
    
    echo "
track gc5Base
shortLabel GC Percent
longLabel GC Percent in 5-Base Windows
group map
priority 5
visibility hide
autoScale on
maxHeightPixels 128:36:18
graphTypeDefault Bar
gridDefault OFF
windowingFunction Mean
color 100,100,100
altColor 100,100,100
spanList 5
type wig 0 100

track contigs
shortLabel Contigs
longLabel GS Assembly contigs
group map
priority 3
visibility hide
color 0,0,0
type bed 6 .
itemRgb on

searchTable contigs
searchType bed
searchMethod fuzzy

track scaffolds
shortLabel scaffolds
longLabel GS Assembly scaffolds
group map
priority 1
visibility hide
color 0,0,0
type bed 9 .
itemRgb on

searchTable scaffolds
searchType bed
searchMethod fuzzy

track gaps
shortLabel Gaps
longLabel GS Assembly gaps
group map
priority 4
visibility hide
color 255,0,0
type bed 4 .

searchTable gaps
searchType bed
searchMethod fuzzy

track depth
shortLabel Read Depth
longLabel Read depth of coverage
group map
priority 5.2
visibility full
autoScale on
maxHeightPixels 128:18:18
graphTypeDefault Bar
windowingFunction Mean
gridDefault OFF
color 100,50,0
altColor 255,128,0
spanList 1,1024
smoothingWindow 4
type wig 0.0 400.0

" > ${CLIENT_TRACKDB_DIR}/${BUILD}/trackDb.ra
   
}

# Setup a password-protected instance of the UCSC Genome Browser
function create_instance {

    # Create web directory to store browser instance
    
    echo "CGB: Create Directories"
    if ( mkdir "$CLIENT_BROWSER_ROOT" );
    then
	    echo "CGB: Creating target directory ${CLIENT_BROWSER_ROOT}."
    else
        echo "CGB: Target directory already exists or you do not have permissions to create it."
        exit 1;
    fi
    
    if ( mkdir "$CLIENT_TRACKDB_DIR" );
    then
	    echo "CGB: Creating target directory ${CLIENT_TRACKDB_DIR}."
    else
        echo "CGB: Target directory already exists or you do not have permissions to create it."
        exit 1;
    fi
    
    if ( mkdir "$CLIENT_GBDB_DIR" );
    then
	    echo "CGB: Creating target directory ${CLIENT_GBDB_DIR}."
    else
        echo "CGB: Target directory already exists or you do not have sufficient priviledges to create it."
        exit 1;
    fi

    echo "CGB: Extracting UCSC Genome Browser binaries ..."
    # Extract browser template, set permissions
    tar -C $CLIENT_BROWSER_ROOT/ -xzf $BROWSER_WEB_TEMPLATE_DIST
    chgrp -R apache $CLIENT_BROWSER_ROOT/js
    mkdir -p $CLIENT_BROWSER_ROOT/trash
    chgrp -R apache $CLIENT_BROWSER_ROOT/trash
    chmod -R 775 $CLIENT_BROWSER_ROOT/js
    chmod -R 775 $CLIENT_BROWSER_ROOT/trash

    # Setup password
    echo "CGB: ** YOUR INPUT IS REQUIRED **"
    echo "CGB: CREATE a password for CLIENT_NAME ${CLIENT_NAME}:"
    until htpasswd -c ${CLIENT_BROWSER_ROOT}/password ${CLIENT_NAME}; do
        echo "CGB: Error setting client password. Retry ..."
    done

    # Setup apache for the client
    echo "CGB: ** YOUR INPUT IS REQUIRED **"
    echo "    COPY THE CODE BELOW AND PASTE INTO YOUR WEB SERVER CONFIG FILE,"
    echo "    e.g. ${APACHE_VHOST}, "
    echo "    JUST ABOVE THE LAST LINE \"</VirtualHost>\"";
    echo "
        # Created using CGB on `date`
        ScriptAlias ${CLIENT_BROWSER_WEBROOT} \"${CLIENT_BROWSER_CGIBIN}\"
        <Directory \"${CLIENT_BROWSER_CGIBIN}\">
            Options ExecCGI +Includes
            # To disable password-protection comment the FOUR lines below,
            # i.e. add a # in front of each line.
            AuthType Basic
            AuthName \"Restricted Files\"
            AuthUserFile ${CLIENT_BROWSER_ROOT}/password
            Require user ${CLIENT_NAME}
       </Directory>
"
   
    echo "CGB: When complete press Enter to continue ..."
    read input
    
    echo "CGB: Restarting apache web server ..."
    echo "CGB: ** YOUR INPUT IS REQUIRED **"
    echo "CGB: This may ask you for your USER or ROOT password"
   
    until ${APACHE_RESTART_CMD}; do
        echo "CGB: Error restarting apache. Retry (y/n)? "
        read ans
        if [ "$ans" = 'n' ];
        then
            break;
        fi
    done

    # Create new hg.conf
    echo "CGB: Setting up hg.conf in ${CLIENT_BROWSER_CGIBIN}"
    echo  "
db.trackDb=trackDb
db.host=${DB_HOST}
db.user=${READONLY_USER}
db.password=${READONLY_PASSWORD}

browser.indelOptions=on

central.db=${CLIENT_HGCENTRAL}
central.host=${DB_HOST}
central.user=${READWRITE_USER}
central.password=${READWRITE_PASSWORD}
central.domain=${APACHE_DOMAIN}

customTracks.host=${DB_HOST}
customTracks.user=${READWRITE_USER}
customTracks.password=${READWRITE_PASSWORD}
customTracks.useAll=yes
customTracks.tmpdir=${CLIENT_BROWSER_ROOT}/tmp


backupcentral.db=${CLIENT_HGCENTRAL}
backupcentral.host=${DB_HOST}
backupcentral.user=${READWRITE_USER}
backupcentral.password=${READWRITE_PASSWORD}
backupcentral.domain=${APACHE_DOMAIN}

browser.documentRoot=${CLIENT_BROWSER_ROOT}

" > ${CLIENT_BROWSER_CGIBIN}/hg.conf

    chmod 444 ${CLIENT_BROWSER_CGIBIN}/hg.conf

   # Create hgcentral database for client
    echo "DROP DATABASE IF EXISTS ${CLIENT_HGCENTRAL}; 
create database ${CLIENT_HGCENTRAL};
use ${CLIENT_HGCENTRAL};
source ${CLIENT_BROWSER_ROOT}/hgcentral.sql;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER on ${CLIENT_HGCENTRAL}.* to ${READWRITE_USER}@${DB_HOST} IDENTIFIED BY '${READWRITE_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER on hgFixed.* to ${READWRITE_USER}@${DB_HOST} IDENTIFIED BY '${READWRITE_PASSWORD}';
GRANT SELECT on ${CLIENT_HGCENTRAL}.* to ${READONLY_USER}@${DB_HOST} IDENTIFIED BY '${READWRITE_PASSWORD}';
GRANT SELECT on hgFixed.* to ${READONLY_USER}@${DB_HOST} IDENTIFIED BY '${READONLY_USER}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER on proteins01.* to ${READWRITE_USER}@${DB_HOST} IDENTIFIED BY '${READWRITE_PASSWORD}';
GRANT SELECT on proteins01.* to ${READONLY_USER}@${DB_HOST} IDENTIFIED BY '${READONLY_USER}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER on customTrash.* to ${READWRITE_USER}@${DB_HOST} IDENTIFIED BY '${READWRITE_PASSWORD}';
;" > $CLIENT_GBDB_DIR/${CLIENT_HGCENTRAL}.sql
    
    echo "CGB: Creating database ${CLIENT_HGCENTRAL}"
    echo "CGB: ** WARNING ** This will replace any existing database with the same name. "
    echo "CGB: ** WARNING ** If unsure, quit this process now my pressing Ctrl-c."
    echo "CGB: ** YOUR INPUT IS REQUIRED **"
    echo "CGB: This may require the MYSQL password"
    until ${MYSQL_CMD} < $CLIENT_GBDB_DIR/${CLIENT_HGCENTRAL}.sql; do
        echo -n "CGB: Invalid Password ... retry? (Y/n): "
        read ans
        if [ "$ans" = 'n' ];
        then
            break;
        fi
    done
    
    echo "CGB: ** TEST THE SETUP **"
    echo "CGB: Navigate to http://${APACHE_DOMAIN}/${CLIENT_BROWSER_WEBROOT}/hgGateway"
    echo "CGB: You will need to enter the password you created for ${CLIENT_NAME}"
    echo "CGB: The webpage should report:"
    echo "     Can\'t find genome \"Human\" in central database table defaultDb."

}

# Remove an instance of the UCSC Genome Browser.
function remove_instance {
    
    echo "CGB: ** YOUR INPUT IS REQUIRED **"
    echo -n "CGB: Are you sure (Y/n): "
    read ans
    if [ "$ans" = 'Y' ];
    then
        rm -Rf $CLIENT_GBDB_DIR $CLIENT_BROWSER_ROOT $CLIENT_TRACKDB_DIR
        
        echo "CGB: ** YOUR INPUT IS REQUIRED **"
        echo "CGB: Enter MYSQL password to drop ${CLIENT_HGCENTRAL}:"
        until ${MYSQL_CMD} -e "drop database if exists ${CLIENT_HGCENTRAL};"; do
            echo -n "CGB: Invalid Password ... retry? (Y/n): "
            read ans
            if [ "$ans" = 'n' ];
            then
                break;
            fi
        done
        echo -e "CGB: Don't forget to:
CGB:\t- Remove the entry in ${APACHE_VHOST}.
CGB:\t- Unload the BLAT servers for the builds.
"
    else
        echo "CGB: See ya."
        exit 0;
    fi
}

# Add, remove, list "clade" entries in hgcentral
function add_clade {
    args=$@
    LABEL=${args[1]}
    NAME=${args[2]}
    PRIORITY=${args[3]}
    
    mysql_hgcentral "INSERT INTO clade (name, label, priority) VALUES ('${NAME}','${LABEL}', ${PRIORITY});"
}

function remove_clade {
    args=$@
    NAME=${args[1]}
    
    mysql_hgcentral "DELETE FROM clade WHERE name = '${NAME}';"
}

function list_clade {
    
    mysql_hgcentral "SELECT g.* FROM clade AS g \G;"
}

# Add, remove, list "genome" entries in hgcentral
function add_genome {
    args=$@
    GENOME=${args[1]}
    CLADE=${args[2]}
    PRIORITY=${args[3]}
    
    mysql_hgcentral "INSERT INTO genomeClade (genome, clade, priority) VALUES ('${GENOME}','${CLADE}',$PRIORITY);"
}

function remove_genome {
    GENOME=$1
    
    mysql_hgcentral "DELETE FROM genomeClade WHERE genome = '${GENOME}';"
}

function list_genome {
    
    mysql_hgcentral "SELECT g.* FROM genomeClade as g \G;"
}


# Add, remove, list "defaultDb" entries in hgcentral
function add_defaultdb {
    args=$@
    GENOME=${args[1]}
    BUILD=${args[2]}
    
    mysql_hgcentral "INSERT INTO defaultDb (genome, name) VALUES ('${GENOME}','${BUILD}');"
}

function remove_defaultdb {
    args=$@
    BUILD=${args[1]}
    
    mysql_hgcentral "DELETE FROM defaultDb WHERE name = '${BUILD}';"
}

function list_defaultdb {
    
    mysql_hgcentral 'SELECT g.* FROM defaultDb AS g \G;'
}

# Add a genome build
function add_build {
    args=$@
    BUILD=${args[1]}
    BUILD_DESC=${args[2]}
    GENOME=${args[3]}
    CHROM=${args[4]}
    FULL_NAME=${args[5]}
    REFERENCE=${args[6]}
    TAXID=${args[7]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    
    if ls -d ${TRACKDB_DIR}/*/${BUILD} > /dev/null 2>&1
    then 
        echo "CGB: ** ERROR ** A build with this name already exists for this or another CLIENT_NAME."
        exit 1;
    fi

    if ( mkdir "${BUILD_DIR}" );
    then
	    echo "CGB: Creating target directory ${BUILD_DIR}."
        mkdir ${CLIENT_GBDB_DIR}/${BUILD}/html
    else
        echo "CGB: Target directory already exists or you do not have permissions to create it."
        exit 1;
    fi
    
    echo "CGB: Executing MySQL commands."
    echo "INSERT INTO dbDb (name, description, nibPath, organism, defaultPos, active, orderKey, genome, scientificName, htmlPath, hgNearOk, hgPbOk, sourceName, taxId) VALUES ('${BUILD}','${BUILD_DESC}','${BUILD_DIR}','${GENOME}', '${CHROM}',1,1,'${GENOME}','${FULL_NAME}','${BUILD_DIR}/html/description.html', 1, 1,'${REFERENCE}', ${TAXID});
INSERT INTO gdbPdb (genomeDb, proteomeDb) VALUES ('${BUILD}','proteins01');
" > ${CLIENT_GBDB_DIR}/${BUILD}/hgcentral_${BUILD}.sql
    
    echo "CGB: ** YOUR MYSQL PASSWORD POSSIBLY REQUIRED **"
    mysql_hgcentral "source ${BUILD_DIR}/hgcentral_${BUILD}.sql;"
    until ${MYSQL_CMD} -e "create database ${BUILD}; GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER on ${BUILD}.* to browser@localhost IDENTIFIED BY 'genome'; GRANT SELECT on ${BUILD}.* to readonly@localhost IDENTIFIED BY 'access';"; do
        echo -n "CGB: Invalid Password ... retry? (Y/n): "
        read ans
        if [ "$ans" = 'n' ];
        then
            break;
        fi
    done
    
 
}

# Remove a build
function remove_build {
    args=$@
    BUILD=${args[1]}
    
    mysql_hgcentral "DELETE FROM dbDb WHERE name = '${BUILD}'; DELETE FROM gdbPdb WHERE genomeDb = '${BUILD}';"
    echo "CGB: ** YOUR MYSQL PASSWORD POSSIBLY REQUIRED **"
    until ${MYSQL_CMD} -e "DROP DATABASE IF EXISTS ${BUILD};"; do
        echo -n "CGB: Invalid Password ... retry? (Y/n): "
        read ans
        if [ "$ans" = 'n' ];
        then
            break;
        fi
    done
    rm -Rf ${CLIENT_GBDB_DIR}/${BUILD}
    rm -Rf ${CLIENT_TRACKDB_DIR}/${BUILD}
}

# List genome build for client
function list_build {
    
    mysql_hgcentral 'SELECT g.* FROM dbDb AS g \G;'
}

# start BLAT servers and add row entriies
function add_blat {
    args=$@
    BUILD=${args[1]}
    BLAT_PORT1=${args[2]}
    BLAT_PORT2=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    
    mysql_hgcentral "INSERT INTO blatServers (db, host, port, isTrans, canPcr) VALUES ('${BUILD}', 'localhost', ${BLAT_PORT1}, 0, 1); \
    INSERT INTO blatServers (db, host, port, isTrans, canPcr) VALUES ('${BUILD}', 'localhost', ${BLAT_PORT2}, 1, 0);"
    CWD=`pwd`
    echo "CGB: Starting up BLAT servers"
    cd ${BUILD_DIR}
    /usr/bin/nohup gfServer start localhost $BLAT_PORT1 ${BUILD}.2bit -stepSize=5  -canStop &
    sleep 1
    /usr/bin/nohup gfServer start localhost $BLAT_PORT2 ${BUILD}.2bit -stepSize=5  -trans -canStop &
    cd $CWD
}

# Stop BLAT servers and delete row entries
function del_blat {
    args=$@
    BUILD=${args[1]}
    BLAT_PORT1=${args[2]}
    BLAT_PORT2=${args[3]}
    
    mysql_hgcentral "DELETE FROM blatServers WHERE db = '${BUILD}';"
    echo "CGB: Stopping servers in memory"
    echo "CGB: Stopping server at port $BLAT_PORT1"
    gfServer stop localhost $BLAT_PORT1
    sleep 2
    echo "CGB: Stopping server at port $BLAT_PORT2"
    gfServer stop localhost $BLAT_PORT2
    sleep 2
   
}

function restart_blat {
    args=$@
    BUILD=${args[1]}
    BLAT_PORT1=${args[2]}
    BLAT_PORT2=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    CWD=`pwd`
    
    echo "CGB: Stopping server at port $BLAT_PORT1"
    gfServer stop localhost $BLAT_PORT1
    sleep 2
    echo "CGB: Stopping server at port $BLAT_PORT2"
    gfServer stop localhost $BLAT_PORT2
    sleep 2
    echo "CGB: Starting up BLAT servers"
    cd ${BUILD_DIR}
    /usr/bin/nohup gfServer start localhost $BLAT_PORT1 ${BUILD}.2bit -stepSize=5  -canStop &
    sleep 1
    /usr/bin/nohup gfServer start localhost $BLAT_PORT2 ${BUILD}.2bit -stepSize=5  -trans -canStop &
    cd $CWD
}

# List BLAT databases for the client
function list_blat {
    
    mysql_hgcentral 'SELECT g.* FROM blatServers AS g \G;'
}

# add a 454 assembly to a genome build. Sorts contigs my length
function add_454_assembly {
    args=$@
    BUILD=${args[1]}
    CHROM=${args[2]}
    ASSEMBLY_DIR=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    
    mkdir ${CLIENT_TRACKDB_DIR}/${BUILD}
    chmod -R 755 ${BUILD_DIR}
        
    # Create chrom, contigs.bed and gaps.bed
    python ${SCRIPT_DIR}/chromByLen.py ${ASSEMBLY_DIR}/454LargeContigs.fna ${CHROM} ${BUILD_DIR} > ${BUILD_DIR}/${BUILD}.fasta
    chmod 755 ${BUILD_DIR}/${BUILD}.fasta
    faToTwoBit ${BUILD_DIR}/${BUILD}.fasta ${BUILD_DIR}/${BUILD}.2bit
    
    # Load chrom
    hgsql ${BUILD} < ${KENT_LIB}/grp.sql
    # DEPRECATED AS OF 17.01.2012
    # hgsql ${BUILD} -e "load data local infile \"${KENT_LIB}/grp.txt\" into table grp;"
    hgsql ${BUILD} < ${KENT_LIB}/chromInfo.sql
    twoBitInfo ${BUILD_DIR}/${BUILD}.2bit stdout | awk -v TWOBIT="$BUILD_DIR/$BUILD.2bit" '{ print sprintf("%s\t%s\t", $1, $2) TWOBIT }' | perl -p -e "s/\/\//\//g;" > ${BUILD_DIR}/chromInfo.tab
    hgsql ${BUILD} -e "load data local infile \"${BUILD_DIR}/chromInfo.tab\" into table chromInfo;"

    # Reload trackDb.ra
    init_trackDb
    CWD=`pwd`
    cd ${TRACKDB_DIR}
    make alpha DBS=${BUILD}
    cd $CWD
    
    #Load assembly tracks
    hgLoadBed ${BUILD} contigs ${BUILD_DIR}/contigs.bed
    hgLoadBed ${BUILD} gaps ${BUILD_DIR}/gaps.bed
    
    # GC Percent
    echo "Creating track: GC Percent"
    mkdir ${BUILD_DIR}/wib/
    hgGcPercent -wigOut -doGaps -file=stdout -win=5 ${BUILD} ${BUILD_DIR} | wigEncode stdin ${BUILD_DIR}/gc5Base.wig ${BUILD_DIR}/wib/gc5Base.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} gc5Base ${BUILD_DIR}/gc5Base.wig
    
    
    # Depth
    echo "Creating track: Read Detpth"
    echo "variableStep  chrom=chrI" > ${BUILD_DIR}/depth.bed
    python ${SCRIPT_DIR}/coverage.py ${BUILD_DIR}/contigs.bed ${ASSEMBLY_DIR}/454AlignmentInfo.tsv | sort -k 1 -n >> ${BUILD_DIR}/depth.bed
    wigEncode ${BUILD_DIR}/depth.bed ${BUILD_DIR}/depth.wig ${BUILD_DIR}/wib/depth.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} depth ${BUILD_DIR}/depth.wig
    
    # Reload trackDb.ra
    # CWD=`pwd`
    # cd ${TRACKDB_DIR}
    # make alpha DBS=${BUILD}
    # cd $CWD
}

# Add a fasta file to a genome build (useful if not a 454 run)
function add_fasta {
    args=$@
    BUILD=${args[1]}
    CHROM=${args[2]}
    FASTA=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    
    if ! mkdir -p ${CLIENT_TRACKDB_DIR}/${BUILD};
    then
        echo "Cannot create build directory.";
        exit 1;
    fi
    chmod -R 755 ${BUILD_DIR}
        
    # Create chrom
    if ! cp $3 ${BUILD_DIR}/${BUILD}.fasta;
    then
        echo "Cannot copy fasta file to build directory.";
        exit 1;
    fi
    chmod 755 ${BUILD_DIR}/${BUILD}.fasta
    faToTwoBit ${BUILD_DIR}/${BUILD}.fasta ${BUILD_DIR}/${BUILD}.2bit
    
    # Load chrom
    echo "1"
    hgsql ${BUILD} < ${KENT_LIB}/grp.sql
    # echo "2"
    # DEPRECATED AS OF 17.01.2012
    # hgsql ${BUILD} -e 'load data local infile "${KENT_LIB}/grp.txt" into table grp;'
    echo "3"
    hgsql ${BUILD} < ${KENT_LIB}/chromInfo.sql
    echo "4"
    twoBitInfo ${BUILD_DIR}/${BUILD}.2bit stdout | awk -v TWOBIT="$BUILD_DIR/$BUILD.2bit" '{ print sprintf("%s\t%s\t", $1, $2) TWOBIT }' | perl -p -e "s/\/\//\//g;" > ${BUILD_DIR}/chromInfo.tab
    echo "5"
    hgsql ${BUILD} -e "load data local infile \"${BUILD_DIR}/chromInfo.tab\" into table chromInfo;"

    # Reload trackDb.ra
    CWD=`pwd`
    cd ${TRACKDB_DIR}
    echo "6"
    make alpha DBS=${BUILD}
    cd $CWD
    
    echo "7"
    init_trackDb
    
    # GC Percent
    echo "Creating track: GC Percent"
    mkdir ${BUILD_DIR}/wib/
    hgGcPercent -wigOut -doGaps -file=stdout -win=5 ${BUILD} ${BUILD_DIR} | wigEncode stdin ${BUILD_DIR}/gc5Base.wig ${BUILD_DIR}/wib/gc5Base.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} gc5Base ${BUILD_DIR}/gc5Base.wig
    
    # Reload trackDb.ra
    CWD=`pwd`
    cd ${TRACKDB_DIR}
    make alpha DBS=${BUILD}
    cd $CWD
}

function add_454scaffold_assembly {

    args=$@
    BUILD=${args[1]}
    CHROM=${args[2]}
    ASSEMBLY_DIR=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/

    mkdir ${CLIENT_TRACKDB_DIR}/${BUILD}
    chmod -R 755 ${BUILD_DIR}

# Create chrom

    python ${SCRIPT_DIR}/sort_agp.py ${ASSEMBLY_DIR} > ${BUILD_DIR}/454Scaffolds.sorted.txt
    python ${SCRIPT_DIR}/build_scaffold.py ${BUILD_DIR}/454Scaffolds.sorted.txt ${BUILD_DIR}
    cat ${BUILD_DIR}/contigs.bed ${BUILD_DIR}/gaps.bed | sort -k2n > ${BUILD_DIR}/assembly.bed
    python ${SCRIPT_DIR}/chrom.py ${BUILD_DIR}/assembly.bed ${ASSEMBLY_DIR}/454AllContigs.fna > ${BUILD_DIR}/${BUILD}.fasta

    chmod 755 ${BUILD_DIR}/${BUILD}.fasta
    faToTwoBit ${BUILD_DIR}/${BUILD}.fasta ${BUILD_DIR}/${BUILD}.2bit

    # Load chrom
    hgsql ${BUILD} < ${KENT_LIB}/grp.sql
    # hgsql ${BUILD} -e "load data local infile \"${GBDB_DIR}/grp.txt\" into table grp;"

    hgsql ${BUILD} < ${KENT_LIB}/chromInfo.sql
    twoBitInfo ${BUILD_DIR}/${BUILD}.2bit stdout | awk -v TWOBIT="$BUILD_DIR/$BUILD.2bit" '{ print sprintf("%s\t%s\t", $1, $2) TWOBIT }' | perl -p -e "s/    \/\//\//g;" > ${BUILD_DIR}/chromInfo.tab
    hgsql ${BUILD} -e "load data local infile \"${BUILD_DIR}/chromInfo.tab\" into table chromInfo;"

    # Reload trackDb.ra
    init_trackDb
    CWD=`pwd`
    cd ${TRACKDB_DIR}
    make alpha DBS=${BUILD}
    cd $CWD

    #Load assembly tracks
    hgLoadBed ${BUILD} contigs ${BUILD_DIR}/contigs.bed
    hgLoadBed ${BUILD} gaps ${BUILD_DIR}/gaps.bed
    hgLoadBed ${BUILD} scaffolds ${BUILD_DIR}/scaffolds.bed

    # GC Percent
    echo "Creating track: GC Percent"
    mkdir ${BUILD_DIR}/wib/
    hgGcPercent -wigOut -doGaps -file=stdout -win=5 ${BUILD} ${BUILD_DIR} | wigEncode stdin ${BUILD_DIR}/gc5Base.wig ${BUILD_DIR}/wib/gc5Base.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} gc5Base ${BUILD_DIR}/gc5Base.wig

    # Depth
    echo "Creating track: Read Detpth"
    echo "variableStep  chrom=chrI" > ${BUILD_DIR}/depth.bed
    python ${SCRIPT_DIR}/coverage.py ${BUILD_DIR}/contigs.bed ${ASSEMBLY_DIR}/454AlignmentInfo.tsv | sort -k 1 -n >> ${BUILD_DIR}/depth.bed
    wigEncode ${BUILD_DIR}/depth.bed ${BUILD_DIR}/depth.wig ${BUILD_DIR}/wib/depth.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} depth ${BUILD_DIR}/depth.wig
}
# Add only the read depth
function add_depth 

{
    args=$@
    BUILD=${args[1]}
    CHROM=${args[2]}
    ASSEMBLY_DIR=${args[3]}
    BUILD_DIR=${CLIENT_GBDB_DIR}/${BUILD}/
    mkdir ${CLIENT_TRACKDB_DIR}/${BUILD}
    chmod -R 755 ${BUILD_DIR}

# Depth
    
    echo "Creating track: Read Depth"
    echo "variableStep  chrom=chrI" > ${BUILD_DIR}/depth.bed
    python ${SCRIPT_DIR}/coverage.py ${BUILD_DIR}/contigs.bed ${ASSEMBLY_DIR}/454AlignmentInfo.tsv | sort -k 1 -n >> ${BUILD_DIR}/depth.bed
    wigEncode ${BUILD_DIR}/depth.bed ${BUILD_DIR}/depth.wig ${BUILD_DIR}/wib/depth.wib
    hgLoadWiggle -pathPrefix=/ ${BUILD} depth ${BUILD_DIR}/depth.wig
}

# Update environment variables when CLIENT_NAME changes.
function update_env {
    CLIENT_GBDB_DIR=${GBDB_DIR}/${CLIENT_NAME}
    CLIENT_BROWSER_ROOT=${BROWSER_WEB_HOME}/browser-${CLIENT_NAME}
    CLIENT_BROWSER_WEBROOT=${APACHE_BROWSER_ROOT}/browser-${CLIENT_NAME}/cgi-bin
    CLIENT_BROWSER_CGIBIN=${BROWSER_WEB_HOME}/browser-${CLIENT_NAME}/cgi-bin
    CLIENT_HGCENTRAL=hgcentral_${CLIENT_NAME}
    CLIENT_TRACKDB_DIR=${TRACKDB_DIR}/${CLIENT_NAME}
}

## PROGRAM MENU

function usage {
    echo -e "cgb -- a program to a create custom instance of the UCSC Genome Browser.

\t NOTE:
\t   To set the CLIENT_NAME: export CLIENT_NAME=DrWatson
\t   All COMMANDs are specific to the current CLIENT_NAME.

\t COMMAND          ARGUMENTS    -- Description
\t -------          ---------------------------
\t create_browser   no arguments -- Create a browser instance.
\t remove_browser   no arguments -- Remove a browser instance.

\t add_clade        CLADE_LABEL CLADE_NAME PRIORITY -- add a clade entry to pulldown menu.
\t remove_clade                 CLADE_NAME          -- remove a clade entry.
\t list_clade       List clades.

\t add_genome       GENOME CLADE_NAME PRIORITY -- Add a genome entry to pulldown menu. 
\t remove_genome    GENOME                     -- Remove a genome entry.
\t list_genome      List genomes.              -- List genomes.

\t add_build        BUILD BUILD_DESC GENOME CHROM SPECIES SOURCE TAXID -- Add a genome build to the browser.
\t remove_build     BUILD                    -- Remove a build.
\t list_build       List builds.

\t add_fasta        BUILD CHROM FASTA_FILE   -- Add a fasta file to a build.

\t add_defaultdb    GENOME BUILD -- Add the a defaultDb entry to pulldown menu. 
\t remove_defaultdb        BUILD -- Remote a defaultDb entry. 
\t list_defaultdb   List defaultDbs.

\t add_blat         BUILD BLAT_PORT1 BLAT_PORT2. Create and load BLAT servers. 
\t remove_blat      BUILD BLAT_PORT1 BLAT_PORT2. Remove and unload BLAT servers.
\t restart_blat     BUILD BLAT_PORT1 BLAT_PORT2. Restart BLAT servers. 
\t list_blat        List BLAT servers.

EXTRA COMMANDS:
\t add_454          BUILD CHROM ASSEMBLY_DIR -- Add 454 assembly contigs to a build.
\t add_454_scaffold BUILD CHROM ASSEMBLY_DIR -- Add 454 assembly scaffolds to a build.
\t add_depth        BUILD CHROM ASSEMBLY_DIR -- Add depth to a build.

\t --help           Print this message.
"
}

# Validate number of commandline arguments 
function validate_args {
    REQ_ARGS=$1
    if [ $NARGS -ne $REQ_ARGS ];
    then
        echo "CGB: ** ERROR ** Task \"${TASK}\" requires $REQ_ARGS arguments."
        echo "CGB: For help see \"cgb --help\""
        exit 1;
    fi
    task_message
}

NARGS=$#

if [ -z "$CLIENT_NAME" ]; then
    echo "CGB: ** ERROR ** CLIENT_NAME must be set to a value, e.g. export CLIENT_NAME=DrWho"
    exit 1;
else
    update_env
    echo -e "CGB: Client name is currently set to \"${CLIENT_NAME}\""
fi

args=("$@")
TASK=${args[0]}

case "$TASK" in
    'show_client')
    	echo Client name: $CLIENT_NAME
	    ;;
    'create_browser')
        validate_args 1
        create_instance
        ;;
    'remove_browser')
        validate_args 1
        remove_instance
        ;;
    'add_clade')
        validate_args 4
        add_clade ${args[1]} ${args[2]} ${args[3]}
        ;;
    'remove_clade')
        validate_args 2
        remove_clade ${args[1]}
        ;;
    'list_clade')
        validate_args 1
        list_clade
        ;;
    'add_genome')
        validate_args 4
        add_genome ${args[1]} ${args[2]} ${args[3]}
        ;;
    'remove_genome')
        validate_args 2
        remove_genome ${args[1]}
        ;;
    'list_genome')
        validate_args 1
        list_genome
        ;;

    'add_defaultdb')
        validate_args 3
        add_defaultdb ${args[1]} ${args[2]}
        ;;
    'remove_defaultdb')
        validate_args 2
        remove_defaultdb ${args[1]}
        ;;
    'list_defaultdb')
        validate_args 1
        list_defaultdb
        ;;
    'add_build')
        validate_args 8
        add_build ${args[1]} ${args[2]} ${args[3]} ${args[4]} ${args[5]} ${args[6]} ${args[7]}
        ;;
    'add_454')
        validate_args 4
        add_454_assembly ${args[1]} ${args[2]} ${args[3]}
        ;;
    'add_454_scaffold')
        validate_args 4
        add_454scaffold_assembly ${args[1]} ${args[2]} ${args[3]}
        ;;
    'add_fasta')
        validate_args 4
        add_fasta ${args[1]} ${args[2]} ${args[3]}
        ;;
    'remove_build')
        validate_args 2
        remove_build ${args[1]}
        ;;
    'list_build')
        validate_args 1
        list_build
        ;;
    'add_blat')
	    validate_args 4
	    add_blat ${args[1]} ${args[2]} ${args[3]}
        ;;
    'remove_blat')
        validate_args 4
        del_blat ${args[1]} ${args[2]} ${args[3]}
        ;;
    'restart_blat')
	    validate_args 4
	    add_blat ${args[1]} ${args[2]} ${args[3]}
        ;;
    'list_blat')
        validate_args 1
        list_blat
        ;;
    'add_depth')
       validate_args 4
       add_depth ${args[1]} ${args[2]} ${args[3]}
       ;;
    '--help')
        usage
        ;;
    '')
        echo "CGB: ** ERROR ** No arguments supplied. Try cgb --help."
        ;;
    *)
        echo -e "CGB: ** ERROR ** Invalid command: $TASK. For help, try \"cgb --help\"."
        ;;
esac

exit 0;

